name: Model Training Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ['lstm', 'transformer', 'autoformer']
        horizon: [90, 365]
      fail-fast: false
      max-parallel: 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone Autoformer if needed
      if: matrix.model == 'autoformer'
      run: |
        git clone https://github.com/thuml/autoformer.git external/autoformer
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/external/autoformer" >> $GITHUB_ENV

    - name: Run training
      run: |
        echo "Running ${{ matrix.model }} model with ${{ matrix.horizon }}-day horizon"
        python main.py --model ${{ matrix.model }} -H ${{ matrix.horizon }}
